
//FOR PRODUCT LIST BABE
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'



//FOR PRODUCT DETAILS BABE
export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAIL_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAIL_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAIL_FAIL'

//IT'S FOR BEST PRACTICES
//EVERY API HAS 3 PHASES
//1ST TO REQUEST
// IN RESPONSE WE WILL GET SUCCESS OR FAIL